-- Populate tags table
INSERT INTO tags (tag) VALUES
                           ('Dungeons & Dragons'),
                           ('Pathfinder'),
                           ('Shadowrun'),
                           ('Call of Cthulhu'),
                           ('GURPS'),
                           ('Vampire: The Masquerade'),
                           ('Cyberpunk 2020'),
                           ('Star Wars RPG'),
                           ('Warhammer Fantasy'),
                           ('Savage Worlds'),
                           ('Dungeon World'),
                           ('The One Ring'),
                           ('Mutants & Masterminds'),
                           ('Legend of the Five Rings'),
                           ('Rifts'),
                           ('Paranoia'),
                           ('Blades in the Dark'),
                           ('Apocalypse World'),
                           ('Starfinder'),
                           ('The Dark Eye'),
                           ('Hero System'),
                           ('Fantasia'),
                           ('Medieval'),
                           ('SI-FI'),
                           ('Horror'),
                           ('Steampunk'),
                           ('Cyberpunk'),
                           ('Super-Heróis'),
                           ('Investigação'),
                           ('Mistério'),
                           ('Ação'),
                           ('Aventura'),
                           ('Terror'),
                           ('Suspense'),
                           ('Drama'),
                           ('Comédia'),
                           ('Fantasia'),
                           ('Ficção Científica'),
                           ('Policial'),
                           ('Guerra'),
                           ('Espionagem'),
                           ('Urbana'),
                           ('Épica'),
                           ('Sombria'),
                           ('Heroica'),
                           ('Mitológica'),
                           ('Oriental'),
                           ('Espacial'),
                           ('Pós-Apocalíptica');